name: ci-cd

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: action/checkout@v1
      - name: setup
        uses: action/setup@v1
        with:
          distribution: 'temurin'
        java-version: '17'
      - name: Build and Test
        run: mvn clean tests